### ISSUE TITLE
Excessive writing to eON log causes some lag during loading

### ISSUE THREAD

**Issue by shmerl** [virtual-programming/witcher2-linux#102]
Since I get a lot of messages in eon.txt of this type:

    Trying to access something that's not a regular file or folder

it slows things down in some places, or so it seems at least. Is there any way to disable logging altogether? I can then compare performance and check if that's indeed an issue.

And I wonder if that warning message is caused by the fact that I'm using a large XFS partition (1.9 TB). It's known to produce weird results for some 32 bit API calls for working with filesystem. They can be prevented with -D_FILE_OFFSET_BITS=64 when compiling. It's just a guess.

**Comment by vpltd-peterm** [comment]
This warning is what happens when the target is actually a symlink instead of a file or a dir. I think one of our developers put it in early on as a warning, and it's been forgotten about. It's harmless otherwise.

We should already be using 64-bit off_t

**Comment by shmerl** [comment]
But is there any way to control loggin level in eON? Or for example disabling it altogether when not needed? Any environment variables?

**Comment by vpltd-peterm** [comment]
Not externally, no

**Comment by shmerl** [comment]
Could be a good feature in general.

**Comment by vpltd-peterm** [comment]
Pretty much all of the debug messages are only of use for debugging eON internally, and are optimised out in Release builds, so only Warnings and Errors are logged, for things that may be diagnostically important on end-user's systems. 

In this case, this particular warning can go away :)

**Comment by vpltd-peterm** [comment]
It seems that this was actually the result of XFS returning DT_UNKNOWN, as such it should no longer occur as we now detect and work around this.

**Comment by shmerl** [comment]
Yeah, I see these warning are gone in the newest beta. Thanks!
