### ISSUE TITLE
Can't load save or start new game

### ISSUE THREAD

**Issue by cberkenpas** [virtual-programming/witcher2-linux#103]
I've had this problem with the following builds:
503099
517988

When attempting to load a game or start a new game, I get the loading screen (the music plays), and I see the spinning snake in the bottom right hand corner of the screen. After a while, the snake will stop spinning, and I'll see a flash on the screen as if something is about to happen. Unfortunately, the game just stays stuck on the loading screen (the little snake no longer spins). Usually the load music just plays as normal, but occasionally that locks up too and it keeps repeating itself very quickly.

This happens less often if I choose medium settings. It _always_ happens with high settings and when I use __GL_THREADED_OPTIMIZATIONS=1, it always happens regarding of the settings.

When the game does run, I get the same stuttering problem as mentioned by others here. Every few seconds of so, the game stutters. On my system, it's quite jarring.

Could be a driver issue with immature Maxwell support in linux?

Netrunner 14 (basically just Kubuntu 14.04)
64-bit
EVGA GTX 980 Classified 
Nvidia drivers version 346.35
i7 5960x
32GB ram
Kernel 3.18.6 (I tried with 3.13, same issue)
In case it matters, I'm using Gsync

**Comment by vpltd-peterm** [comment]
it's quite possible. If you have a dual monitor setup, open a terminal on one screen, start Witcher 2 normally, and in the other type "top -H -p `pidof witcher2`". Keep watching the threads CPU usage, and see if one starts hogging CPU.

Sound looping over and over sounds like the PCI-E bus is being stalled, preventing the sound card receiving new sound data from Pulse/ALSA/OSS/whatever. This would definitely point to a driver issue.

**Comment by cberkenpas** [comment]
I'll just ssh in from my laptop. I'll try to find a window of time to do 
this within the next few days.

**Comment by cberkenpas** [comment]
I forgot I had an extra computer with almost the same GPU (EVGA GTX 980 SC on the other computer as opposed to EVGA GTX 980 Classified on my primary machine).

The game runs extremely well on this other computer. It looks like my other computer is victim to this issue:
http://www.phoronix.com/forums/showthread.php?113111-PCIe-bus-errors-on-Linux-with-GTX-980

Which would explain the occasional sound looping issue as it seems there's an issue with X99 boards and the PCIE controller (unclear if it's a general problem or specifically something that occurs with Nvidia GPU's, and it seems some windows users are or at least were affected too).

The specs of my affected system:
i7 5960x
Asus Rampage V Extreme (X99 chipset)
EVGA GTX 980 Classifiedd
32GB Memory

The specs of my working system:
i7 4960x
Asus Rampage IV (X79 chipset)
EVGA GTX 980 SC
32GB Memory

Here's what I've tried with the working system (all cases with vsync and a 60 Hz monitor):
Medium Specs: 60 fps
Medium Specs+__GL_THREADED_OPTIMIZATIONS=1: 60 fps
High Specs+__GL_THREADED_OPTIMIZATIONS=1: 60 fps
Ultra Specs+__GL_THREADED_OPTIMIZATIONS=1: 30 fps (includes uber sampling of course)

Although theoretically I should be able to get 60 fps (or above) with either system on Ultra (at least in windows), I am more than happy to play through the game on "only" high specs! Fantastic work getting The Witcher 2 running so well under Linux with the eon wrapper!

I'm closing this issue out as it seems that this isn't a witcher 2 bug (and probably needs a BIOS update to correct). Thanks!
