### ISSUE TITLE
Crash reports for this application are not currently being accepted.

### ISSUE THREAD

**Issue by psi29a** [virtual-programming/witcher2-linux#105]
This is what I got when trying to send a crash report.

This is the output:
https://gist.github.com/psi29a/681c1f26102c09fb6c7c

**Comment by vpltd-peterm** [comment]
Yeah, we have some downtime on the server that runs our crash collection endpoint. We're working on it. Should be resolved by tomorrow hopefully.

**Comment by vpltd-peterm** [comment]
This should now be fixed and we are receiving bug reports correctly

**Comment by psi29a** [comment]
Since I've not encountered a crash in a week, it is hard to reproduce this now. ;)  Cheers!
