### ISSUE TITLE
Game crashes during start-up

### ISSUE THREAD

**Issue by andreamaritan** [virtual-programming/witcher2-linux#113]
Hi, 

game doesn't start at all - it seems a problem related to "gameoverlay".

I tried to disable game overlay on Steam, but the problem persists.

Here is my crash report. Can you help me fixing it?

http://paste.ubuntu.com/10561452/

Thank you

**Comment by licaon-kter** [comment]
Those are normal errors regarding the overlay, ignore them.
What build of the game are you using ? ( right click on Witcher2 -> Advanced -> Local Files -> last line of text ) 

If you are not using the Latest Beta (Release Candidate) - Steam BuildID 547552 then do enable it BETA -> opt in *linux_public_beta* -> Ok, wait for it to update -> retry

**Comment by vpltd-peterm** [comment]
Yeah, this is due to the kernel problem #89 and it's been fixed in the beta

**Comment by andreamaritan** [comment]
Using the Beta, I confirm that the game now works. Thank you.
