### ISSUE TITLE
Bioshock Infinite bug tracker? 

### ISSUE THREAD

**Issue by ekianjo** [virtual-programming/witcher2-linux#117]
Thanks Everyone at VP and Peter for the work done on Bioshock Infinite for Linux - it's a great release and it runs very well overall. I know this is not the right place for this, but do you plan to do a github tracker for the bugs of the Bioshock:Infinite linux port? 

It would be a great idea and I have already a few minor issues to report - better to keep them in one place if possible. 

Feel free to close this right after you answer :)

**Comment by shmerl** [comment]
I hope 2K won't try forbidding anything like that.

**Comment by vpltd-peterm** [comment]
It's in the works...

**Comment by licaon-kter** [comment]
And one for SpecOps: The Line maybe? :D

**Comment by vpltd-peterm** [comment]
Will open one soon - it would have been done for release, but I had to attend a family funeral

**Comment by licaon-kter** [comment]
Sorry to hear that, hope everything works out right.

**Comment by licaon-kter** [comment]
https://www.phoronix.com/scan.php?page=article&item=dirt-2-linux&num=1

DIRT Showdown Github issues repo planned?
