### ISSUE TITLE
Witcher 2 does not free memory when quiting the game

### ISSUE THREAD

**Issue by ragingkid** [virtual-programming/witcher2-linux#120]
It seems that when you exit the game, it does not free system memory. The only workaround I found is to use this in command line:
  sudo sysctl -w vm.drop_caches=3
I use:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty 
Kernel version 3.13.0-46-generic

**Comment by vpltd-peterm** [comment]
What you are referring to here is simply read-ahead cache memory. This is not the same as process memory. This will be freed and re-used by the system as appropriate.

This is not a bug.
