### ISSUE TITLE
Text dissapears after saving

### ISSUE THREAD

**Issue by roranicus** [virtual-programming/witcher2-linux#122]
This is an issue I've been having for a long time. Whenever I save the game, a certain number of characters will simply dissapear. For example, every instance of the letter "R" of a certain size will no longer show up. This can be limited to one or two letters, or make everything unreadable. The exact effect is random. 

Reinstalling the game fixes it for one game session. After I quit and return to the game, the issue comes back. This bug happens with the vanilla version of the game, patch 1.0.0.4 and patch 1.1.0.5.

OS is Linux Mint 17 Xfce, 64bits. 
Processor: Intel i7 2600, 3.4GHz
Graphics: AMD Radeon HD 6950

**Comment by licaon-kter** [comment]
Does removing the *fontconfig* folder help? So you don't reinstall the game that is.

**Comment by roranicus** [comment]
It did not change anything, I just tried it and the issue still occurs.

**Comment by vpltd-peterm** [comment]
"fontconfig" is generated by GTK apps, so by the configurator.. it is not part of the game.

The only thing I can immediately think of is to perform a Steam verify when this happens and see if files  need to be redownloaded. If they do, this points more towards the files getting corrupted on disk.

Also please indicate which graphics driver and version you are using.

**Comment by roranicus** [comment]
I do not use steam, I have the gog version.

As for the driver, it's fglrx version 2:13.350.1

**Comment by vpltd-peterm** [comment]
That is a very old version of fglrx, and is not supported by the game. You should update to at least 14.4, or preferably 14.12 (Omega).

**Comment by roranicus** [comment]
That fixed the problem, thanks! I feel kinda silly now.
