### ISSUE TITLE
st/nine: Direct3D 9 State Tracker from Mesa.

### ISSUE THREAD

**Issue by cheako** [virtual-programming/witcher2-linux#123]
Every now and then there is a new development, reported to have significant impact on some applications.  In this case D3D9 applications.

One such feature is the advent of a native Linux Direct3D Nine Libraries that are receiving active development and testing.
http://www.mesa3d.org/relnotes/10.4.3.html

It should be possible to adapt eON to make use of this new API instead of it's wrapper/translator around OpenGL.  I'd like to test such an adaptation.

Against the use of [DFSG-incompatible](https://wiki.debian.org/DFSGLicenses#Licenses_that_are_DFSG-incompatible) software when [DFSG-compatible](https://wiki.debian.org/DFSGLicenses#The_Big_DFSG-compatible_Licenses) alternatives are available.  Will not install or test non-free video drivers, since 1998.
https://wiki.debian.org/DFSGLicenses

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x30
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  4100 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    
\* Note: This is a AMD A10-7850K APU with Radeon(TM) R7 Graphics, for future CrossFireX testing.
** There is another R7 GPU in this system that is the primary display.
Network Information:
    Network Speed:  
    
*** 1GB, ~7Mb down 128Kb up DSL.
Operating System Version:
    Debian GNU/Linux 8.0 (jessie) (****64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  i3
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
**** Actually running "Debian GNU/Linux 8.0 (jessie) (32 bit)" only the kernel is AMD64.
cheako@arcadia:~$ dpkg --print-architecture 
i386
cheako@arcadia:~$ dpkg --print-foreign-architectures 
cheako@arcadia:~$ 
Video Card:
    Driver:  X.Org Gallium 0.4 on AMD CAPE VERDE
    Driver Version:  3.0 Mesa 10.3.2
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x683d
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 73.70" x 41.46"  (84.53" diag)
                                            187.2cm x 105.3cm  (214.7cm diag)
    Primary VRAM Not Detected

***** R7 250X 2GB DDR5, this _is_ the 2GB ASUS card.
****** UHDTV 55' Sony with no stereoscopics(does not 3D support glasses).
HDMI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 1872mm x 1053mm
   4096x2160     24.00    23.98  
   3840x2160     30.00    25.00    24.00    29.97    23.98  
Sound card:
    Audio device: Realtek ALC1150
    
******* Optical 7.1 channel Sony Receiver DTS and AC-3 capable.
******** Pulseaudio.
Memory:
    RAM:  15957 Mb
    
Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  196608 Mb
    Largest Free Hard Disk Block:  114334 Mb
    
Installed software:
    
Recent Failure Reports:
    Mon Mar 23 16:23:24 2015 GMT: file ''/tmp/dumps/crash_20150323112323_2.dmp'', upload no: ''Failure when receiving data from the peer''

**Comment by vpltd-peterm** [comment]
This was discussed in #90
