### ISSUE TITLE
MESA 10.3.2(Debian Jessie for example) falls back to OpenGL 2.1 renderer.

### ISSUE THREAD

**Issue by cheako** [virtual-programming/witcher2-linux#124]
Tested MESA 10.4.2(current Sid) and eon.txt reports "OpenGL Core context version 3.3 detected" even though steam still claims OpenGL is 3.0.

OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.4.2
OpenGL version string: 3.0 Mesa 10.4.2

**Comment by vpltd-peterm** [comment]
We do not officially support the Mesa driver, but the r600g driver should support the OpenGL 3.2 backend correctly. radeonsi and nouveau should also support it, but are not performant enough to work well.
