### ISSUE TITLE
Game can not be used through in-home streaming

### ISSUE THREAD

**Issue by zerodogg** [virtual-programming/witcher2-linux#129]
I have attempted to stream The Witcher 2 from a Linux host to several Linux clients. The launcher works, however as soon as the game starts proper, the screen turns black. Other games work, oddly enough, including Bioshock Infinite and Spec Ops: The Line.

The host is an Arch Linux 64bit machine, clients are Ubuntu 14.04 64bit, and Arch Linux 64bit. The game itself works fine on the host machine, but for some reason the stream is black.

**Comment by vpltd-peterm** [comment]
Does The Witcher 2 function correctly ?

**Comment by zerodogg** [comment]
The game runs great on the host, and it displays on the host when the streaming is active, but the stream is black. Playing the other two VP ports through in-home streaming works without any problems.

**Comment by vpltd-peterm** [comment]
Strange.. I have no idea why this would be, as spec ops uses exactly the same Direct3D 9 code that Witcher 2 uses.

I'd suggest this is more likely to be a bug in Steam's streaming, and you should report this to Valve for investigation by them.

**Comment by vpltd-peterm** [comment]
Strange.. it is likely this is a problem with Steam's streaming though, rather than our game. I would suggest you report this issue to Valve.
