### ISSUE TITLE
Game crashes when trying to delete game saves.

### ISSUE THREAD

**Issue by nbieter** [virtual-programming/witcher2-linux#130]
I have had a lot of problems with the game crashing at random intervals and looking at the issue tracker here, I thought it might be the game save memory leak issue. Although I checked the size of my game save files and it was only 96 mb, I still tried to wipe the saves clean to see if I could run the game properly. I have found a reproducible bug where, upon successfully deleting one save and trying to delete a second save, It crashes. 

My specs are:

OS: Linux Mint 17.1
CPU: AMD FX-6300
GPU: Nvidia 750 ti (running drivers 349)

**Comment by licaon-kter** [comment]
Delete (or better move) them **outside** the game.

**Comment by nbieter** [comment]
I cannot seem to find them in my program files. I have uninstalled and reinstalled the game and they appear to be connected to the steam cloud; should I disable steam cloud saves?

**Comment by licaon-kter** [comment]
Try:
**$XDG_DATA_HOME/cdprojektred/witcher2/GameDocuments/Witcher\ 2/gamesaves/**
or the cloud
**~/.steam/steam/userdata/[user id]/20920/remote**

**Comment by nbieter** [comment]
I meant in the cdprojecktred gamesaves file. :)

I found it in the .steam userdata though. Thanks for giving me the filepath.

**Comment by ekianjo** [comment]
By the way I confirm I have experienced the same issue: deleting games saves in-game causes crashes.

**Comment by blastermaster77** [comment]
me too i try to delete save files and it crashes.

**Comment by licaon-kter** [comment]
Yep, original game issue, delete them from outside the game.

**Comment by vpltd-peterm** [comment]
Unfortunately yes, this happens in the Windows original too, so we cannot do anything about it

**Comment by vpltd-peterm** [comment]
Closing as original game bug we cannot fix
