### ISSUE TITLE
Game crashes when using force_s3tc_enable=true

### ISSUE THREAD

**Issue by boffo25** [virtual-programming/witcher2-linux#131]
I'm using OpenSuse 13.2, with mesa 10.6 rc, Mesa R600. The game with steam starts, goes to the menu and the after I press the new game bottom it crashes.
I use the following options LIBGL_DEBUG=verbose SDL_AUDIODRIVER=alsa force_s3tc_enable=true /usr/bin/steam.
The error in the console is
*** BREAKPAD CRASH ***
ERROR: ld.so: object '/home/X/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/X/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
pid 6586 != 6553, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/X/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/home/X/.local/share/Steam/SteamApps/common/the witcher 2/CrashReporter.x86_64: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/X/.local/share/Steam/SteamApps/common/the witcher 2/CrashReporter.x86_64)
Game removed: AppID 20920 "The Witcher 2: Assassins of Kings Enhanced Edition", ProcID 6553.
It crashes with no info because the libstdc it needs is too old.

When I remove the options force_s3tc_enable=true
The game works, but (obviously) with no textures.

<a href="http://postimg.org/image/jpxnpti6d/" target="_blank"><img class="bbcode-attachment" src="http://s18.postimg.org/jpxnpti6d/witcher2.jpg" border="0" alt="" /></a>

With the following errors
EE r600_state_common.c:766 r600_shader_select - Failed to build shader variant (type=1) -12
EE r600_shader.c:2527 r600_shader_from_tgsi - GPR limit exceeded - shader requires 148 registers
EE r600_shader.c:158 r600_pipe_shader_create - translation from TGSI failed !

Does anybody know what should I do?

**Comment by licaon-kter** [comment]
Use https://gist.github.com and paste the contents of:
```
$XDG_DATA_HOME/cdprojektred/witcher2/eon.txt
```

**Comment by boffo25** [comment]
with force_s3tc_enable=true
https://gist.github.com/5166710d64888a4f802e.git
without force_s3tc_enable=true
https://gist.github.com/6b0d173d1b9f8d41e30b.git

**Comment by vpltd-peterm** [comment]
In a folder in /tmp you should also find the Google Breakpad mindump file. You may also run the game through GDB and get a backtrace.

However, please note that we do not officially support the Mesa drivers. S3TC/DXT texture support is required by the game to work correctly. If there are bugs in Mesa's support for this, it will crash the game.

**Comment by boffo25** [comment]
My bad. I forgot to install libtxc_dxtn 32 bit. Now the games runs fine. I had the libtxc_dxtn 64 bit installed and I don't know how the other games where working with the 64 bit instead of the 32 bit.
