### ISSUE TITLE
Switching from Linux to Windows

### ISSUE THREAD

**Issue by fenuks** [virtual-programming/witcher2-linux#138]
I would like to switch from Linux version of The Witcher II to Windows one for performance reasons.
I have radeon 7770 and Witcher II crashes with fglrx driver, RadeonSI on the other hand works good, but with limited performance. Do I have to re-download whole game or it is possible to get only Windows executables (which is preferred)?

**Comment by vpltd-peterm** [comment]
The "CookedPC" folder contains most of the game data, and is identical to the Windows release. However as for obtaining the Windows executables other than by official means, we cannot help you.

**Comment by licaon-kter** [comment]
@fenuks: Steam or GoG?
If Steam just copy the contents as Steam will replace the Linux part with Windows files ( ~125Mb ), don't forget to delete the *launcher* file first though.

**Comment by fenuks** [comment]
Thank you for the fast reply. I have GoG version, so I'll check if GoG Galaxy can download missing files.

**Comment by licaon-kter** [comment]
Do share your experience, no Linux client no go. :P

**Comment by fenuks** [comment]
It is possible to download missing files. In your library select Witcher II, click `more -> manage -> Import Folder`. Note that, it seems that folder layout is different under Linux (`<Witcher II folder>/game/CookedPC`) than Windows (`<Witcher II folder>/CookedPC`) so you need to cut `CookedPC` folder to Witcher II root folder before importing it to GoG Galaxy client or it will attempt to re-download whole game. In my case I need to download additional ~5Gb. Cheers.
I consider it solved, it can be closed now. Thank you.
