### ISSUE TITLE
NPC dialogue menus sometimes stop responding to mouse movement.

### ISSUE THREAD

**Issue by ali1234** [virtual-programming/witcher2-linux#144]
Sometimes during an NPC conversation the menu will not respond to mouse movement. This means that the top choice remains highlighted regardless of where I move the mouse. If I click anywhere on the screen including on other items the top choice will happen. This seems to happen most often with the innkeeper/storage guy in Vergen who has dice poker as his top option, but seems like it can happen with any NPC. I have seen it happen under both 14.04 and 15.04. As a workaround you can still choose an option with the keyboard.

**Comment by vpltd-peterm** [comment]
Original game issue we cannot fix. Closing.
