### ISSUE TITLE
Game over/continue screen sometimes ignores mouse input.

### ISSUE THREAD

**Issue by ali1234** [virtual-programming/witcher2-linux#145]
After you die the game asks "Do you want to load the most recent save? (yes/no)." Sometimes this screen will not accept any mouseinput. The options do not highlight when you move the mouse over them and clicking on them does nothing. Seen under both 14.04 and 15.04. Workaround: press escape.

**Comment by vpltd-peterm** [comment]
Bug in the original game. Closing.
