### ISSUE TITLE
Mouse wheel scrolls lists by more than the number of visible items.

### ISSUE THREAD

**Issue by ali1234** [virtual-programming/witcher2-linux#146]
If you use the mousewheel to scroll your inventory, or the shop inventory, or any of the various other lists which don't fit on one screen, they will scroll by greater than the number of visible items. That is, some items will be skipped. This makes it very difficult to find things in your inventory if it's the item that gets skipped and you don't realise what is happening. I *think* it scrolls by number of visible items + 1, meaning one items gets skipped each time you scroll.

**Comment by vpltd-peterm** [comment]
This is the same as the Windows version, so we cannot change it. Closing.
