### ISSUE TITLE
Can't access the main menu - Escape key does nothing.

### ISSUE THREAD

**Issue by ali1234** [virtual-programming/witcher2-linux#148]
This one is very rare. For some reason I can't press escape to access the main menu/pause the game. This has literally never happened before and I am currently well in to act three. As a result of this I can't save or load the game. At the moment I have both a USB and a PS/2 keyboard connected to test the other input bug, and Escape works on neither.

**Comment by ali1234** [comment]
After I died I was able to reload my last save which wasn't too far back. After reloading the escape key worked again and after I retraced my steps I wasn't able to reproduce this. I originally noticed the problem after taking the shortcut back to the surface after Secrets of Loc Muinne.

**Comment by vpltd-peterm** [comment]
Closed as cannot be reproduced
