### ISSUE TITLE
Witcher 2 crashes on current Debian testing / KDE Plasma 5 (Nvidia driver 355.06).

### ISSUE THREAD

**Issue by shmerl** [virtual-programming/witcher2-linux#149]
I just downloaded the latest update from GOG:

    The Witcher 2: Assassins Of Kings - Enhanced Edition
    2.2.0.8
    Release 3 (20150306204412)

and it crashes on startup on my Debian testing x86_64 (KDE Plasma 5 with KWin/X11 compositor using GLX, Nvidia driver: 355.06).

See [application log report](https://gist.github.com/anonymous/03b9a4dae1ec6ed08ee5).

Let me know if you need any more details or what to test further.

**Comment by shmerl** [comment]
Some report a similar issue, even without KDE. See [here](https://www.gog.com/forum/general/general_linux_faq_and_troubleshooting/post392) and [here](https://www.gog.com/forum/general/general_linux_faq_and_troubleshooting/post396).

**Comment by Armored87** [comment]
This seems to a game problem, not OS. I tested the game on the following systems:

1. Mint 17.1 64bit - Mate Desktop / Geforce GTX 960 with drivers v352.30 / Kernel 3.13

2. OpenSUSE 13.2 64bit Xfce Desktop / Geforce GTX 760 with drivers v352.30 / Kernel 3.16

Launching the game produces a black screen which lasts less than half a second and closes down immediately (On both systems) and the terminal outputs the following error:

*** BREAKPAD CRASH ***
/home/jojo/Main/Games/The Witcher 2/game/CrashReporter.x86_64: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/jojo/Main/Games/The Witcher 2/game/CrashReporter.x86_64)

**Comment by licaon-kter** [comment]
@Armored87: Do you have libtxc_dxtn 32 bit installed ?

The crashreporter error is not essential. what does **strings /usr/lib/libstdc++.so.6 | grep GLIBCXX** output?

**Comment by shmerl** [comment]
OK, this bug is invalid. The issue is really with GOG package of the game. You can't use game data as is after extracting it. One file is split in three there (the biggest one), so you need to merge it first which is done by the installer script. I extracted it as is, that's why it was crashing. That was quite unexpected.

If you are in a similar situation, to make it work, do this (from the location where you unpacked the game).

    cd game/CookedPC
    cat pack0.dzip.split* > pack0.dzip
    rm pack0.dzup.split*
