### ISSUE TITLE
Not work on SteamOS 2.70

### ISSUE THREAD

**Issue by linuxgamer91** [virtual-programming/witcher2-linux#161]
Hello, I have the game installed on my Alienware Steam Machine with newest SteamOS, at the start nothing happened. A change to the beta has not helped.

It starts but it appears only a black bar at the edge of the screen, the Steam Overlay can be opened more but does not.

**Comment by licaon-kter** [comment]
Can you get a console (switch to desktop) and try to start it there as:

**Comment by vpltd-peterm** [comment]
Closing due to no feedback
