### ISSUE TITLE
libgcrypt 1.6.1-32 and 1.7.1

### ISSUE THREAD

**Issue by Mehrnimmer** [virtual-programming/witcher2-linux#169]
Having a Crash on Opensuse  Leap42.1, that with libgcrypt 1.6.1 32 only gives a mark in Konsole that it is a bug, and with 1.7.1(sorry 1.7.3-125.1) it opens the Crashhandler.

what ever libgcrypt does, its having a bug, the files working with having a Bug, or files/programms that have a Bug, are only interacting buggy with a Bugreporting and libgcrypt, if this lib is only for the Bugreporter in,

but i think its the Way the property of the Steamgamefiles is secured, right?

So there lies a little the dead rotten white rabbit in the Wheat Fields.

**Comment by vpltd-peterm** [comment]
You reported the same matter on Overlord. libgcrypt is not used by the game, but it is used by Mesa.
Closing as this is not a game bug.
