### ISSUE TITLE
Black transition when texture pops in

### ISSUE THREAD

**Issue by Markussss** [virtual-programming/witcher2-linux#170]
I'm currently running Fedora 24 on an i5 2500k with 12GB RAM and a R9 390, using the most up-to-date version of mesa available (from https://copr.fedorainfracloud.org/coprs/mystro256/polaris-gfx/).

My problem is that whenever a texture switches between quality (pops in or out), it goes black for a moment before fading in or out. Here is a short video I recorded to show the issue I'm having. I recorded this on lowest quality preset to make video recording a little more smooth. https://www.youtube.com/watch?v=ocLMmXnqiQg. 

As I'm running an experimental driver for my card, I'm aware that this _might_ be a pure driver issue that goes away if I go back to using the older open source radeon-driver or the proprietary amdgpu-pro-driver. However, I wanted to ask here if there is anything I can do to make the texture transitions _not_ touch black.

I have tried searching for this issue online, but it seems like not many other people have this issue, or they haven't asked much about it. I've tried all possible combinations of settings on the options-GUI, different OpenGL-versions, etc.

Thanks for your time. Have a lovely day.

**Comment by vpltd-peterm** [comment]
AS far as we know, this is a problem with the current version of Mesa radeonsi that has not yet been resolved. The issue is not present on either AMD's Catalyst driver, or Nvidia's driver. WE have not tried it with the AMDGPU-PRO driver yet.

**Comment by Markussss** [comment]
Thanks a lot, Peter! I was hoping I wouldn't have to remove the drivers, but it works flawlessly now. I'm closing the issue, as your answer resolves my issue (although the issue is still present in the current version of mesa).
