### ISSUE TITLE
Very inappropriate User.ini - Settings

### ISSUE THREAD

**Issue by 4l4l2I2M1** [virtual-programming/witcher2-linux#172]
The settings on ultra in the User.ini are far from something that suits ultra(even for the time of its release). For example the memory budget is far too little, the mesh distance is extremely near the caracter...
This doesn't just worsen the image quality but also makes the current radeonsi texture changing bug extremely visible, see:
https://github.com/virtual-programming/witcher2-linux/issues/170
https://bugs.freedesktop.org/show_bug.cgi?id=98238

It would be really nice if the game launcher could write appropriate settings that suit the real memory budget and load more textures withing a long distance and perhaps if it was possible to bind the grass textures on this value as well, as it is suggested in the bug comments on freedesktop.org. It wouldn't just improve the image quality for most users who don't edit their ini files, but also make it smoother and the bug wouldn't even be visible that much until it's fixed as I estimate most of these changes to be pretty easy.

**Comment by vpltd-peterm** [comment]
The settings come from the original Windows settings. We were told to leave them as is.

As far as we're concerned, the bug in Mesa should be fixed - it is not a game bug as the problem does not show up on either the nvidia driver or AMD's Catalyst driver.

**Comment by 4l4l2I2M1** [comment]
Thanks for the immediate answer! Of course I appreciate your situation although I feel a bit sad about the game that you have to leave these values as they are because it gives somehow worse gameplay experiences as it could, especially with exceeded video memory on higher resolutions. However beside that I am really convinced about your work so wherever you are allowed to make your own decisions carry on and bring more nice games to linux ;)
