### ISSUE TITLE
constant crash on debian 8 / AMD graphics 15.302

### ISSUE THREAD

**Issue by kennyngston** [virtual-programming/witcher2-linux#174]
Hi,

After 6-7 hours of gameplay I encountered constant crashes around entering new areas, or just within a random <2 minutes of gameplay.

I updated to latest catalyst, deleted all but one save games, set everything to low, and am running the steam build 765819 - but the issue still occurs.

I've attached the screenshot of amdcc showing the exact version I'm running, also the eon.txt.

Please let me know if there is any more info I can gather, I would like to play this game :)

Thanks!

The crash report ID is: MGTBGSJX0P
lspci: https://gist.github.com/kennyngston/fe0fdfb0270cf337d9f864a2dbf292d8
report details: https://gist.github.com/kennyngston/a0018848933b94849707951f41a391d4

[eon.txt](https://github.com/virtual-programming/witcher2-linux/files/636399/eon.txt)
![amdccc](https://cloud.githubusercontent.com/assets/1654557/20964763/25b8f1ae-bc73-11e6-88ab-f981d164b2ce.png)

**Comment by vpltd-kgalaj** [comment]
The game is crashing on jump to 0x0 when executing one of the OpenGL commands, but there's no more information available in the log. Possibly a change of graphics card driver would help?

**Comment by kennyngston** [comment]
Thanks for the prompt response! I did that about an hour ago, when I upgraded to latest driver - the issue was the same with the old driver. Can you advise on which version I should try?

**Comment by vpltd-kgalaj** [comment]
Can you try with those? https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers

**Comment by kennyngston** [comment]
yeah, let me switch and I'll get back to you. Thanks.

**Comment by vpltd-peterm** [comment]
At this point I would recommend switching to the Mesa radeonsi driver. Im not sure how up to date this is on Debian Jessie. If you can find a recent 13.x series build, that would likely work quite well.

**Comment by vpltd-peterm** [comment]
It looks like Debian Jessie's default Mesa version is the 10.x series... this is far too old. You absolutely need something from the 12.x series - i'd recommend 12.0.4. Im afraid I have no guidelines on how to get this onto Debian.

**Comment by kennyngston** [comment]
Ok, with mesa 10 from Debian repos (https://packages.debian.org/source/jessie/mesa) it was working without crash (well, only one crash upong exit), but poor performance, so that can be a possible solution. I tried to install mesa 12 from backport (https://packages.debian.org/source/jessie-backports/mesa) which broke my graphics completely - I'll try to get this working over the weekend and update this thread. For now I can only recommend NOT to install mesa on Debian by building from source directly :)

**Comment by kennyngston** [comment]
I've managed to get it working with Mesa 12. Unfortunately 3-4 hours of gameplay it crashed when I entered another area through a door.
Crash ID: 00IRAPW4R8
Crashlog: https://gist.github.com/kennyngston/93028ab41e5a9d3f7f6c6bd4e5346064
lspci hasn't changed.
eon.txt attached.
[eon.txt](https://github.com/virtual-programming/witcher2-linux/files/640457/eon.txt)

**Comment by vpltd-kgalaj** [comment]
Does this crash always happen when entering that area through a door? There's nothing to go on in the crash log.

**Comment by kennyngston** [comment]
I wasn't able to reproduce that specific crash. I think this can be marked as resolved with workaround, workaround being to use mesa 12 under Debian from backports.

**Comment by shmerl** [comment]
If you try installing Mesa from source ol older distro, you'd also need to have compatible amdgpu driver (i.e. newer kernel), libdrm-amdgpu and libllvm libraries. And that potentially will require pulling in new xorg and etc. It's all is kind of messy to install.
