### ISSUE TITLE
Dialog audio is missing, lips don't move

### ISSUE THREAD

**Issue by h3xx** [virtual-programming/witcher2-linux#59]
The characters seem to be communicating telepathically. The subtitles are there, but none of the characters' lips move, and the voice track isn't playing. All other sound works just fine.

Console output: https://gist.github.com/h3xx/b72e71d5861b136c7434

Are there any missing system libraries that could be causing this? I thought I installed all the required 32-bit libs but I might be wrong. (Similar-scale games like Metro Last Light work fine with current 32-bit set)

**Comment by shmerl** [comment]
The latest beta (for GOG users) still has this problem and writes
    Speech=EN
To User.ini when you run the configurator, which makes a mismatch with the voice file. Same fix as above applies.

**Comment by vpltd-peterm** [comment]
Can you confirm again what file system you're using ? I cannot reproduce this on my own systems, which are using ext4

**Comment by shmerl** [comment]
I'm using XFS. Also, my partition size is 1.9 TB which introduces a number of unexpected effects for different 32 bit applications.

**Comment by vpltd-peterm** [comment]
OK, well eON itself should be 64 bit clean, as we are using the 64 bit versions of filesystem API's where appropriate, with off_t and size_t as 64-bit sized vars. This is mainly because this is the default on the Mac, and I ensured it should also be this way on Linux.

I will check if the game itself is using the 64-bit clean file API's, but it should be as there are .dzip files which are larger than 4GB, and the game requires >4GB filesystem support to work on Windows (ie, NTFS).

I will see if i can set up XFS and replicate the problem here

**Comment by shmerl** [comment]
Interestingly, on large ext4 partitions that problem ([with Grim Fandango](https://www.gog.com/forum/grim_fandango_remastered/grim_fandango_remastered_fails_to_run_on_linux)) didn't appear. It's something XFS specific. I can try testing TW2 it on 2 TB ext4 partition on my end to verify if there is any difference.

**Comment by vpltd-peterm** [comment]
Please do. If it is an XFS specific issue, we can either look at working around it, or reporting it as a bug

**Comment by shmerl** [comment]
Yep, I just tested it on 2 TB ext4 external hard drive. And DLC window is not empty anymore! Apparently it has something to do with XFS (and probably large partition).

**Comment by shmerl** [comment]
I just run the game from 2 TB ext4 partition (but my User.ini is still on 1.9 TB XFS partition - that's where my $HOME is). Audio still isn't working when setting is Speech=EN.

**Comment by vpltd-peterm** [comment]
Hmm, could you make one more test ? Put the data on XFS but symlink ~/.local/share/cdprojektred/witcher2 to an ext4 partition? This would greatly narrow things down...

**Comment by shmerl** [comment]
OK, I moved $HOME/.local/share/cdprojektred to ext4 partition (from XFS one) and symlinked it back to the XFS. The problem is till there - no speech in the game.

**Comment by vpltd-peterm** [comment]
To update this for others, the problem seems to be specific to the XFS file system. We are currently not sure why this is. Ext4 is not affected.

**Comment by vpltd-peterm** [comment]
Testing this on XFS now, to see if i can discover what the problem is

**Comment by vpltd-peterm** [comment]
We are indeed using the d_type field of dirent in a few places, and this looks like it will be impacting our case insensitive matching code. This explains the problem.

As noted elsewhere, I consider lack of support for d_type a bug in XFS. Still, I will work around it.

**Comment by vpltd-peterm** [comment]
Please re-test this with the beta released today, the problem should be solved

**Comment by shmerl** [comment]
I can confirm that speech in the dialogs now works even when setting is Speech=EN as done by the configurator tool.
