### ISSUE TITLE
Latest beta - narration audio doesn't play

### ISSUE THREAD

**Issue by Benedolt** [virtual-programming/witcher2-linux#68]
Since the latest beta patch, audio narration doesn't work any more. I still see the subtitles in the handdrawn flashback scenes but only hear the background music playing. The same is true for Dandelion's narration when the world map is shown between the acts.

I'm on Ubuntu 14.04, Intel i3-3220, Nvidia GTX660. Any logs or data I can give you to help?

(Apart from this issue and the crashes on exit the new beta runs much better! I was able to crank up the graphics settings!)

**Comment by vpltd-peterm** [comment]
Have now looked into this more thoroughly and it seems to be an issue with our memory manager. It is not related to bug #59

For some reason, only the cut scenes rendered by the Scaleform middleware seem to be affected. This manifested itself when I cut down our "reserved memory size" to a much lower value. 

So far it seems if I set this to 512M reserved things work as expected, so the next beta will ship with that. However it warrants further investigation...

**Comment by ajgp** [comment]
Thanks for looking at this;  any chance of the Beta being available for GOG users? if so where can I download it.

**Comment by vpltd-peterm** [comment]
It is available now :)

**Comment by vpltd-peterm** [comment]
Can people confirm that this is fixed with Beta 5?

**Comment by mirandir** [comment]
It's fixed here. Thanks!

**Comment by Benedolt** [comment]
Works here as well. Thank you! :)
