### ISSUE TITLE
missing libraries

### ISSUE THREAD

**Issue by githostage** [virtual-programming/witcher2-linux#69]
I use arch and bought the game through gog today.

Installed it and patched it. But then i had to download or copy libraries from steam folder because they arent provided with the game.
Tried my best doing this, but now im stuck with this

./witcher2: /usr/lib32/libldap_r-2.4.so.2: no version information available (required by ./libcurl.so.4)
./witcher2: /usr/lib32/liblber-2.4.so.2: no version information available (required by ./libcurl.so.4)
./witcher2: /usr/lib32/libssl.so.1.0.0: no version information available (required by ./libcurl.so.4)
./witcher2: /usr/lib32/libssl.so.1.0.0: no version information available (required by ./libcurl.so.4)
./witcher2: /usr/lib32/libcrypto.so.1.0.0: no version information available (required by ./libcurl.so.4)
CrashReporter: /usr/lib32/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by CrashReporter)

So the library from my system is to new for this game.
However i copied libcurl.so.4 from steam into the witcher game directory witch solved this error:

/usr/lib32/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./witcher2)

How do i proceed? And why arent libs delivered with the game because of such issues?

more information about the problems: http://www.gog.com/forum/the_witcher_2/the_linux_version_of_the_witcher_2_is_out/page2

**Comment by vpltd-peterm** [comment]
Next version of the game will ship with a new crash reporter which loads libcurl at runtime, and should be able to work with a variety of different libcurl versions.

**Comment by vpltd-peterm** [comment]
Additionally, the game's reliance on libcurl will be removed with the next update. It was originally used for a SOAP service of some kind which the game no longer uses.

**Comment by anadon** [comment]
Sweet.
