### ISSUE TITLE
Corrupted savegames when starting from a non-writable folder

### ISSUE THREAD

**Issue by mirandir** [virtual-programming/witcher2-linux#75]
Hello,

I have a strange problem with the Linux version of The Witcher 2.
When I start the game from a non-writable folder (for example /opt/the_witcher_2/), the game doesn't save games properly.
.sav files in ~/.local/share/cdprojektred/witcher2/GameDocuments/Witcher 2/gamesaves/ have a size of 32 bytes, and the game cannot load them.

If I copy-paste the game in a writable directory (~/Documents/Games/the_witcher_2/), saving games works as intended.

GOG.com version 1.0.0.4
Arch Linux 64 bits
Nvidia GeForce GT 710M with nvidia driver
Intel Pentium 2117U 1,80 GHz with 4go of RAM
Root and home filesystem use ext4

Example of a corrupted savegame : https://www.dropbox.com/s/7e0etuncl3cb2av/bad_QuickSave.zip

**Comment by vpltd-peterm** [comment]
Yes it would. We will have to improve our file system code so that we can easily redirect such behaviour. It isn't really valid behaviour on Windows either now, since as only administrative users have write permission to Program Files, and only after privilege elevation.

**Comment by vpltd-peterm** [comment]
Please re-test this with the beta released today

**Comment by mirandir** [comment]
I confirm : this problem is solved with latest beta.

**Comment by vpltd-peterm** [comment]
Closed as fixed
