### ISSUE TITLE
Continuous crashes on Fedora 20

### ISSUE THREAD

**Issue by gborque** [virtual-programming/witcher2-linux#78]
The game crashes continuously with low settings and 720p, getting SIGSEGV crash during the game.

The specs of my computer are:

Fedora 20 32bit KDE spin
Intel i3 2100
Nvidia GTX 650
Driver 331.89 from RPMfusion

I have tried disabling prelinking and SElinux, but I'm still getting crashes sooner or later.

This is the crash report:

https://gist.github.com/gborque/49c1b8fcf45c208dbed9

If you still need more information, please, feel free to ask.

**Comment by vpltd-peterm** [comment]
Are you still getting this with the latest beta?

**Comment by vpltd-peterm** [comment]
Closing as no reply, and likely due to the known savedgame leak.
