### ISSUE TITLE
Game crashes in Roche's story (Chapter 3?)

### ISSUE THREAD

**Issue by ekianjo** [virtual-programming/witcher2-linux#85]
I am in the camp, in the little sisters quest, and as I head back to the house on the cliff, the game crashes back to desktop at the same spot. I thought this was potentially related to the saves games issue, but even after erasing most of them, it crashes in the same spot again. Here's the eon.txt dump. Does anyone have any idea how to fix this ? 

[thread ffffffff][I][0]: Log system initialised
[thread ffffffff][I][13]: Default allowed number of simultaneously open files in the system is 2448.
[thread ffffffff][I][13]: Current memlock limit is 65536.
[thread ffffffff][I][13]: setrlimit(RLIMIT_MEMLOCK) failed, (1) Operation not permitted
[thread 00000001][I][64]: OpenGL information:
[thread 00000001][I][64]:     renderer: GeForce GTX 460/PCIe/SSE2
[thread 00000001][I][64]:     vendor: NVIDIA Corporation
[thread 00000001][I][64]:     version: 3.2.0 NVIDIA 340.58
[thread 00000001][I][64]:     GLSL version: 1.50 NVIDIA via Cg compiler
[thread 00000004][W][10689]: Game is trying to enable termination on heap corruption. We don't have it implemented at the moment, implement it? This warning will be issued only once per run.
[thread 00000001][I][10732]: Gamepads: joystick with GUID 030000005e0400001907000000010000 (name 'Xbox 360 Wireless Receiver') found
[thread 00000001][I][10732]: Gamepads: joystick has SDL instance id 0
[thread 00000001][I][10732]: Gamepads: joystick with GUID 030000005e0400001907000000010000 (name 'Xbox 360 Wireless Receiver') found
[thread 00000001][I][10732]: Gamepads: joystick has SDL instance id 1
[thread 00000001][I][10732]: Gamepads: joystick with GUID 030000005e0400001907000000010000 (name 'Xbox 360 Wireless Receiver') found
[thread 00000001][I][10732]: Gamepads: joystick has SDL instance id 2
[thread 00000001][I][10732]: Gamepads: joystick with GUID 030000005e0400001907000000010000 (name 'Xbox 360 Wireless Receiver') found
[thread 00000001][I][10732]: Gamepads: joystick has SDL instance id 3
[thread 00000004][W][10754]: eON_LoadLibraryEx() couldn't load 'C:\media\GROS3A\SteamLibrary\SteamApps\common\the witcher 2\bin\telemetry32.dll', returning NULL!
[thread 00000004][W][26518]: REGISTRY OPERATION: RegOpenKeyExW() returns ERROR_NOT_FOUND (subkey not found) key = HKEY_CURRENT_USER, subkey = SOFTWARE\PersonalAudio\MyEars
[thread 00000004][W][34681]: eON_LoadLibraryEx() couldn't load 'LightFX.dll', returning NULL!
[thread 00000004][W][34681]: eON_LoadLibraryEx() couldn't load 'nvapi.dll', returning NULL!
[thread 00000004][W][34778]: eON_LoadLibraryEx() couldn't load 'wintab32.dll', returning NULL!
[thread 00000004][I][34816]: Available video memory: 0
[thread 00000004][I][34816]: Available texture memory: 0
[thread 00000004][W][34860]: PERFORMANCE WARNING: Implicit sync due to enlarging shader vector.
[thread 0000000d][I][34864]: OPENGL: OpenGL thread start
[thread 0000000d][I][34884]: OpenGL backend to Direct3D9: SUMMARY OF FALLBACKS AND INEFFICIENCIES:
[thread 0000000d][I][34884]:  - Anisotropic texture filtering not supported in OpenGL! This may produce incorrect rendering results in game, as other texture filtering modes will be used instead.
[thread 0000000d][I][34884]: OpenGL backend to Direct3D9: END OF SUMMARY
[thread 0000000d][I][34903]: Recommended max number of vertices addressed in one glDrawRangeElements() call: 1048576
[thread 0000000d][I][34903]: Recommended max number of indices addressed in one glDrawRangeElements() call: 1048576
[thread 0000000d][I][34903]: Shader precompilation start: unprepared shaders: 1199, unlinked programs: 1092
[thread 00000004][I][34904]: Max D3D9 surface size is now 8294400
[thread 00000004][I][34908]: This OpenGL driver in this OpenGL context version has no support for texture mirror clamp, and thus may not simulate MIRRORONCE sampling mode!
[thread 0000000d][I][36449]: Shader precompilation finished
[thread 00000004][W][36499]: eON_LoadLibraryEx() couldn't load 'nvapi.dll', returning NULL!
[thread 00000004][W][36499]: Unsupported State D3DRS_LASTPIXEL Value: 0
[thread 00000004][I][36501]: Max D3D9 surface size is now 16588800
[thread 00000004][W][38582]: Game wants keyboard to be EXCLUSIVE. Currently it doesn't work this way in eON.
[thread 00000004][W][38598]: DirectInputKeyboardDevice8Imp::GetDeviceData() returning DIERR_NOTACQUIRED.
[thread 00000004][W][38600]: DirectInputMouseDevice8Imp::GetDeviceState() returning DIERR_NOTACQUIRED.
[thread 00000001][I][39883]: Gamepads: joystick 0 received input, and is from now on considered attached (this is a guard against xpad reporting attached joysticks that aren't there)
[thread 00000001][I][39883]: Gamepads: active joystick is now joystick 0 (this is a guard against xpad not reporting that a joystick has been detached, which would cause a detached joystick to take up forever simulated XInput slot 0, blocking all gamepad control)
[thread 0000000d][I][40199]: Uniform buffer 0xf0ad7be8 now has 2 internal buffers, taking 8192000 bytes
[thread 0000000d][I][40205]: Uniform buffer 0xf0ad7c28 now has 2 internal buffers, taking 8192000 bytes
[thread 0000000e][W][106286]: Unsupported texture format D3DFMT_L6V5U5
[thread 0000000e][W][106311]: Unsupported texture format D3DFMT_X8L8V8U8
[thread 0000000e][W][106384]: Unsupported texture format D3DFMT_A2W10V10U10
[thread 0000000e][W][106410]: Unsupported texture format D3DFMT_Q16W16V16U16
[thread 0000000e][W][106476]: Unsupported texture format D3DFMT_CxV8U8
[thread 0000000e][W][106508]: Unsupported texture format D3DFMT_UYVY
[thread 0000000e][W][106535]: Unsupported texture format D3DFMT_R8G8_B8G8
[thread 0000000e][W][106562]: Unsupported texture format D3DFMT_YUY2
[thread 0000000e][W][106586]: Unsupported texture format D3DFMT_G8R8_G8B8
[thread 0000000d][I][110815]: Uniform buffer 0xf0ad7be8 now has 3 internal buffers, taking 12288000 bytes
[thread 0000000d][I][110832]: Uniform buffer 0xf0ad7be8 now has 4 internal buffers, taking 16384000 bytes
[thread 0000000d][I][112657]: Uniform buffer 0xf0ad7da8 now has 2 internal buffers, taking 294912 bytes
[thread 0000000d][I][123357]: Uniform buffer 0xf0ad7c28 now has 3 internal buffers, taking 12288000 bytes
[thread 0000000d][I][131850]: Uniform buffer 0xf0ad7be8 now has 5 internal buffers, taking 20480000 bytes
[thread 00000001][I][196928]: ===enforcing log flush===
[thread 00000001][I][196928]: Log system shutdown

**Comment by ekianjo** [comment]
Sorry I have not checked your reply for a while here, I plan to attach a savegame here during this week. That should make the bug super easy to reproduce.

**Comment by vpltd-peterm** [comment]
eon.txt indicates a clean shutdown, suggesting it's some sort of game content issue rather than a bug with the port.

**Comment by ekianjo** [comment]
Note that I managed to pass that point in the game after one of the previous beta. You should close this bug, I think.
